setwd("~/Documents/cloga.github.io/notebook")
FORECASTING ELANTRA SALES
elantra = read.csv('elantra.csv')
str(elantra)
train = subset(elantra, (elantra$Year<=2012)==TRUE)
test = subset(elantra, (elantra$Year<=2012)==FALSE)
str(train)
str(test)
train$Month = as.factor(train$Month)
test$Month = as.factor(test$Month)
model = lm(ElantraSales ~ Unemployment + CPI_all + CPI_energy + Queries, data=train)
summary(model)
model = lm(ElantraSales ~ Unemployment + CPI_all + CPI_energy + Queries + Month, data=train)
summary(model)
table(train$Month)
cor(as.numeric(train$Month), train$CPI_energy)
cor(as.numeric(train$Unemployment), train$CPI_energy)
cor(as.numeric(train$Queries), train$CPI_energy)
cor(as.numeric(train$CPI_all), train$CPI_energy)
cor(as.numeric(train$Month), train$Queries)
cor(as.numeric(train$CPI_energy), train$Queries)
cor(as.numeric(train$CPI_all), train$Queries)
model = lm(ElantraSales ~ Unemployment + CPI_all + CPI_energy + Month, data=train)
summary(model)
test_pre = predict(model, newdata = test)
sum((test_pre-test$ElantraSales)*(test_pre-test$ElantraSales))
length(test_pre)
length(test$ElantraSales)
sum((test_pre - mean(train$ElantraSales))**2)
sd(test_pre)**2