name: Cloga的互联网笔记
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments: true
timezone: Asia/Shanghai
encoding: UTF-8
destination: public
exclude: ["CNAME", "Rakefile", "README.md", "public"]
